name: prolif
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ipykernel
  - ipython
  - ipywidgets
  - pandoc
  - pip
  - python
  - rdkit
  - cython
  - nbsphinx
  - networkx
  - recommonmark
  - seaborn
  - sphinx==3.2.1
  - tqdm
  - pip:
    - pyvis
    - py3Dmol
