name: build
on:
  release:
    types: [released]

env:
  PLF_CONDA_DEPS: "rdkit cython"

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.6
        auto-update-conda: true
        channel-priority: flexible
        channels: conda-forge, defaults
        add-pip-as-python-dependency: true
        architecture: x64
    
    - name: Check conda and pip
      run: |
        which python
        python --version
        pip --version
        conda --version

    - name: Install conda dependencies
      env:
        PLF_CONDA_FULL_DEPS: "${{ env.PLF_CONDA_DEPS }}"
      run: |
        conda install ${PLF_CONDA_FULL_DEPS}

    - name: Install package through pip
      run: |
        pip install .
    
    - name: Check setup
      run: |
        pip list
        conda list
    
    - name: Install packaging tools
      run: |
        pip install setuptools wheel

    - name: Build
      env:
        PROLIF_VERSION: ${{ github.event.release.tag_name }}
      run: |
        python setup.py sdist bdist_wheel
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}